variables:
  SONAR_URL: "http://sonar.thed3chain.com:9001/"
  SONAR_LOGIN: 73b833ca4a07ff3b279e4571839c33e9f708028f
  SONAR_EXCLUSIONS: "demo-redis/**/*,demo-mq/**/*"

stages:
  - test

job1:
  stage: test
  tags:
    - sonarqube
  only:
    - merge_requests
    - pushes
  script:
    - sonar-scanner -Dsonar.exclusions=$SONAR_EXCLUSIONS -Dsonar.projectKey=$CI_PROJECT_NAME -Dsonar.host.url=$SONAR_URL -Dsonar.login=admin -Dsonar.password=1zBxKqpacyoq5wr3 -Dsonar.sources=.  -Dsonar.java.binaries=. -Dsonar.java.source=8 -Dsonar.analysis.CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME -Dsonar.analysis.GITLAB_USER_EMAIL=$GITLAB_USER_EMAIL -Dsonar.analysis.GITLAB_USER_NAME=$GITLAB_USER_NAME -Dsonar.analysis.CI_PROJECT_PATH=$CI_PROJECT_PATH -Dsonar.scm.disabled=true
