spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.178:8848
        group: LOCAL
  redis:
    host: 192.168.0.210 # Redis服务器地址
    database: 1 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
# swagger 登录认证
knife4j:
  basic:
    enable: false
    ## Basic认证用户名
    username: admin
    ## Basic认证密码
    password: admin123456
  production: false #默认是false ,屏蔽所有Swagger的相关资源
  enable: true #是否开启swagger

micro:
  info:
    version: 1.0.0
    base-package: com.micro.cloud
  swagger:
    title: OAuth2 后台
    description: OAuth2 后台接口文档
    version: ${micro.info.version}
    base-package: ${micro.info.base-package}.controller