spring.cloud.nacos.discovery.server-addr: 192.168.0.178:8848
spring.cloud.nacos.discovery.group: DEV
#spring.cloud.nacos.discovery.namespace: d54e4b3c-99c0-4f90-b6bf-3c0242c71753

spring.redis.host: 192.168.0.201
spring.redis.port: 6379

ribbon:
  ReadTimeout: 500000
  SocketTimeout: 500000
  ConnectTimeout: 500000