export default [
  {
    addDisabled: false,
    addHide: false,
    columnComment: '',
    columnName: 'jobName',
    type: 'text',
    editDisabled: false,
    editHide: false,
    isSearch: true,
    isShowInTable: true,
    label: '任务名称',
    model: '',
    ruleProp: 'jobName',
    viewHide: false
  },
  {
    addDisabled: false,
    addHide: false,
    columnComment: '',
    columnName: 'jobGroup',
    type: 'text',
    editDisabled: false,
    editHide: false,
    isSearch: true,
    isShowInTable: true,
    label: '任务组',
    model: '',
    ruleProp: 'jobGroup',
    viewHide: false
  },
  {
    addDisabled: false,
    addHide: false,
    columnComment: '',
    columnName: 'jobClassName',
    type: 'text',
    editDisabled: false,
    editHide: false,
    isSearch: true,
    isShowInTable: true,
    label: '类名',
    model: '',
    maxlength: 254,
    ruleProp: 'jobClassName',
    viewHide: false
  },
  {
    addDisabled: false,
    addHide: false,
    columnComment: '',
    columnName: 'cronExpression',
    type: 'text',
    editDisabled: false,
    editHide: false,
    isSearch: false,
    isShowInTable: true,
    label: '表达式',
    model: '',
    ruleProp: 'cronExpression',
    viewHide: false
  }
]
