server:
  port: 9201
spring:
  application:
    name: micro-oauth2-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.107:8848
        group: TEST
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            # 允许携带认证信息
            allow-credentials: false
            # 允许跨域的源(网站域名/ip)，设置*为全部
            allowedOrigins: "*"
            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
            allowedMethods: "*"
            # 允许跨域请求里的head字段，设置*为全部
            allowedHeaders: "*"
      default-filters:
        #相同header多个值时的处理方式，三种规则可选（RETAIN_FIRST|RETAIN_UNIQUE|RETAIN_LAST）
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

      routes: #配置路由路径
        - id: oauth2-api-route
          uri: lb://micro-oauth2-api
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: oauth2-auth-route
          uri: lb://micro-oauth2-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: jiangbeilian-backend
          uri: http://192.168.0.107:8000/
          predicates:
            - Path=/jiangbeilian/**
          filters:
            - StripPrefix=1
        - id: dataresource-backend
          uri: lb://dataresource-backend
          predicates:
            - Path=/dataresource/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://192.168.0.107:9526/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    host: 192.168.0.107 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.ico"
      - "/webjars/springfox-swagger-ui/**"
      - "/system/sms/send-sms-code"
      - "/system/captcha/verify"
      - "/actuator/**"
      - "/auth/oauth/token"
      - "/auth/rsa/publicKey"
      - "/api/sys/user/login"
      - "/api/sys/sms/send-sms-code"
      - "/api/sys/user/individual/register"
      - "/api/sys/user/org/register"
      - "/jiangbeilian/backend/source/topic"
      - "/jiangbeilian/backend/source/data/classify/queryDataClassifyById"
      - "/jiangbeilian/backend/source/data/classify/uploadFile"
      - "/jiangbeilian/backend/source/data/classify/uploadFile2"
      - "/jiangbeilian/backend/apply/application/scene"
      - "/jiangbeilian/backend/advice/track/addAdvice"
      - "/jiangbeilian/backend/advice/track/createCode"
      - "/jiangbeilian/backend/advice/track/detailAdvice"
      - "/jiangbeilian/backend/advice/track/listAdvice"
      - "/jiangbeilian/backend/open/statistics/overview"
      - "/jiangbeilian/backend/open/statistics/platformScanHistory"
      - "/jiangbeilian/backend/open/statistics/topicFavoriteCount"
      - "/jiangbeilian/backend/open/statistics/topicRecordCount"
      - "/jiangbeilian/backend/open/statistics/topicScanAndInvokeCount"
      - "/jiangbeilian/backend/interface/invoke/record/add"
      - "/jiangbeilian/backend/interface/invoke/record/top"
      - "/jiangbeilian/backend/guide/download"
      - "/jiangbeilian/backend/uploadFile"
      - "/jiangbeilian/backend/source/scan/record/add"
      - "/jiangbeilian/backend/source/scan/record/top"
      - "/jiangbeilian/backend/source/directory/left"
      - "/jiangbeilian/backend/source/directory/list"
      - "/jiangbeilian/backend/source/directory/querySourceDetailById"
      - "/jiangbeilian/backend/source/directory/querySourceTitleById"
      - "/jiangbeilian/backend/source/directory/recentUpdData"
      - "/jiangbeilian/backend/source/directory/testRedis"
      - "/jiangbeilian/backend/source/directory/interface/topTenInterInfo"
      - "/jiangbeilian/backend/source/directory/data/sourceDirectoryDataList"
      - "/jiangbeilian/backend/source/directory/file/sourceFileDataPreview"
      - "/jiangbeilian/backend/source/directory/downloadSourceDirectory"
      - "/jiangbeilian/backend/source/directory/dataMaplist"
      - "/api/sys/captcha/get-image"
      - "/api/sys/captcha/get-imageForNum"
      - "/api/sys/user/logout"
      - "/api/sys/user/generate/token"
      - "/api/sys/user/password/reset"
      - "/api/sys/user/login-no-captcha"
      - "/jiangbeilian/backend/apply/source/directory/applicationTemplate/download"
      - "/jiangbeilian/backend/iconDisplay"

micro:
  info:
    version: 1.0.0
    base-package: com.micro.cloud
  swagger:
    title: IPlatform管理后台
    description: 系统管理接口文档
    version: ${micro.info.version}
    base-package: ${micro.info.base-package}.controller

cors:
  allowedorigin: '*'

